name: Go

on:
  push:
    branches: [idea]

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      
    - name: Run test with coverage
      run: go test -race -covermode=atomic -coverprofile=coverage.out

    - name: Publish code coverage badge
      run: |
        set -x
        COVERAGE=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
        if (( $(echo "$COVERAGE <= 50" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$COVERAGE > 90" | bc -l) )); then
          COLOR=green
        else
          COLOR=orange
        fi
        curl "https://img.shields.io/static/v1?label=coverage&message=$COVERAGE%25&color=$COLOR&style=flat-square" > coverage.svg

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0
      with: 
        create_credentials_file: true
        workload_identity_provider: 'projects/1023502242916/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'github-status@psychic-sensor-331908.iam.gserviceaccount.com'

    - id: upload-file
      name: Upload badge to Google Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: coverage.svg
        destination: jkarate/labels