name: Go

on:
  push:
    branches: [idea]

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
      
    - name: Test
      run: go test -race -covermode=atomic -coverprofile=coverage.out

    - id: auth
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with: 
        create_credentials_file: true
        workload_identity_provider: 'projects/1023502242916/locations/global/workloadIdentityPools/github-pool/providers/github'
        service_account: 'github-status@psychic-sensor-331908.iam.gserviceaccount.com'

    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'coverage.out'
        destination: 'jkarate/coverage.out'